[package]
name = "atenia-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
uuid = { version = "1", features = ["v4"] }
rayon = "1.11"
ctor = "0.2"
num_cpus = "1.16"
once_cell = "1.19"
crossbeam-deque = "0.8"
sysinfo = "0.30"
libloading = "0.8"
